### PR TITLE
Better EembassyOS integration

### PR DESCRIPTION
**Pull request by k0gen**
photo_2022-06-19_22-27-17

### CODE REVIEW

**Comment by yzernik** [comment]
Thanks! Trying it out now.

**Comment by yzernik** [comment]
LGTM!

**Comment by chrisguida** [comment]
You guys should submit this to our new service packaging repo!

https://github.com/Start9Labs/service-packaging/issues/new/choose

**Comment by yzernik** [comment]
Thanks @chrisguida I'll have a look

**Pull request merged**
